### ISSUE TITLE
vim completion

### ISSUE THREAD

**Issue by MasseGuillaume** [wedens/vim-scala-completion#1]
this [plugin](https://github.com/megaannum/vimside) uses [ensime](https://github.com/ensime/ensime-server) and offer features like completion

**Comment by wedens** [comment]
it's not maintained and lacks documentation. i'm trying to create something like ensime from scratch. it's interesting thing to create :)

**Comment by MasseGuillaume** [comment]
Yep I noticed that :-)
https://github.com/MasseGuillaume/ScalaKata
https://github.com/CodeBrew-io
